### ISSUE TITLE
About the calibration chessboard

### ISSUE THREAD

**Issue by xmba15** [HViktorTsoi/ACSC#10]
Hi @HViktorTsoi Thank you very much for the project. I have a question related to the checkerboard.
In README, you have mentioned that *There should be no extra borders around the checkerboard*.
Can you elaborate on the reason why it is important to remove the extra borders of the checkerboard?

**Comment by HViktorTsoi** [comment]
Hi, it is because of the cost function we designed, for estimating 3D corners of the checkerboard. You may check our paper, or our implementation here https://github.com/HViktorTsoi/ACSC/blob/fd989bd6ab8833a09171c7edb37e17d58da25c61/calibration.py#L207. 

Unlike 2D corner estimation, we regard the points of the entire checkerboard as a whole cluster, and then fit the 3D corners according to its reflectance distribution. Therefore, if there are extra borders around the board, the points swept to these borders will also gather with the useful checkerboard points(those swept on the white/black squares), and participate in the calculation of the cost function, and these points with unknown reflectivity distribution pattern will affect cost calculation. As a result, the accuracy of 3D corner fitting will be affected.

**Comment by xmba15** [comment]
Thank you for the explanation. If I understand it right, the extra borders will only affect 3D corners detection using lidar point cloud?
If manual steps (by users) to extract point cloud regions of interest are added, i.e. manually removing all the point clouds of the ground and extra borders, can the restriction of having a non-extra-border board be removed?

**Comment by HViktorTsoi** [comment]
> Thank you for the explanation. If I understand it right, the extra borders will only affect 3D corners detection using lidar point cloud?
> If manual steps (by users) to extract point cloud regions of interest are added, i.e. manually removing all the point clouds of the ground and extra borders, can the restriction of having a non-extra-border board be removed?

Yes, the extra borders will only affect 3D corners detection; If extra points are manually removed, then the restriction can be ignored (as long as thera is no extra points feed to the (pointcloud_chessboard_corner_detection)[https://github.com/HViktorTsoi/ACSC/blob/fd989bd6ab8833a09171c7edb37e17d58da25c61/calibration.py#L675] )

**Comment by xmba15** [comment]
@HViktorTsoi that answered my question. Thank you for the clarification.
